/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemenresto.view;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import manajemenresto.controller.HistoryController;
import manajemenresto.model.History;

/**
 *
 * @author anr00
 */
public class FormHistori extends javax.swing.JPanel {
    NumberFormat _f = new DecimalFormat("#0.00");  
    HistoryController hc = new HistoryController();
    History history = new History();
    ArrayList<History> historyList;
    public FormHistori() {
        initComponents();
        updateHistoryTable();
        fillTabelHistory();
    }
public void fillTabelHistory() {
        DefaultTableModel df = (DefaultTableModel)tableHistory.getModel();
        df.getDataVector().removeAllElements();
        if (historyList != null) {
            double total=0;
            int no = 1;
            for (History history: historyList) {
                Object[] obj = new Object[5];
                obj[0] = no;
                obj[1] = history.getId();
                obj[2] = history.getDate();
                obj[3] = history.getTotal_biaya();
                obj[4] = history.getUser_id();
                ++no;
                total+=history.getTotal_biaya();
                df.addRow(obj);
            }
            this.lblTotal.setText("Rp."+_f.format(total));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboFilter = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        sortbox = new javax.swing.JComboBox<>();
        ascrad = new javax.swing.JRadioButton();
        descrad = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(143, 40, 50));

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Mingguan", "Bulanan" }));
        comboFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFilterItemStateChanged(evt);
            }
        });
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filter & Sorting:");

        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Id", "Tanggal", "Total Harga", "Id user"
            }
        ));
        jScrollPane2.setViewportView(tableHistory);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total pendapatan:");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Rp.0");

        sortbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "default", "tanggal", "total biaya" }));
        sortbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortboxActionPerformed(evt);
            }
        });

        ascrad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ascrad.setForeground(new java.awt.Color(255, 255, 255));
        ascrad.setSelected(true);
        ascrad.setText("kecil ke besar");
        ascrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascradActionPerformed(evt);
            }
        });

        descrad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descrad.setForeground(new java.awt.Color(255, 255, 255));
        descrad.setText("besar ke kecil");
        descrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sortbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descrad))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ascrad)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblTotal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descrad)
                                    .addComponent(sortbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(ascrad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void updateHistoryTable(){
        String _sortdirection="";
        if (this.ascrad.isSelected()){
            _sortdirection=this.ascrad.getText();
        }
        else if (this.descrad.isSelected()){
            _sortdirection=this.descrad.getText();
        }
        if (comboFilter.getSelectedItem() == "Semua"){
            System.out.println("Masuk ke semua");
            historyList = hc.getAllHistory(this.sortbox.getSelectedItem().toString(),_sortdirection);
        } else if (comboFilter.getSelectedItem()=="Bulanan"){
            System.out.println("Masuk ke bulan ini");
            historyList = hc.getBulanIniHistory(this.sortbox.getSelectedItem().toString(),_sortdirection);
        } else if (comboFilter.getSelectedItem()=="Mingguan"){
            System.out.println("Masuk ke minggu ini");
            historyList = hc.getMingguIniHistory(this.sortbox.getSelectedItem().toString(),_sortdirection);
        }
        fillTabelHistory();
    }
    private void comboFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFilterItemStateChanged
        updateHistoryTable();
    }//GEN-LAST:event_comboFilterItemStateChanged

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        // TODO add your handling code here:
        updateHistoryTable();
    }//GEN-LAST:event_comboFilterActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        parentFrame.setVisible(false);
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void sortboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortboxActionPerformed
        // TODO add your handling code here:
        updateHistoryTable();
    }//GEN-LAST:event_sortboxActionPerformed

    private void ascradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascradActionPerformed
        // TODO add your handling code here:
        this.descrad.setSelected(false);
        updateHistoryTable();
    }//GEN-LAST:event_ascradActionPerformed

    private void descradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descradActionPerformed
        // TODO add your handling code here:
        this.ascrad.setSelected(false);
        updateHistoryTable();
    }//GEN-LAST:event_descradActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascrad;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JRadioButton descrad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> sortbox;
    private javax.swing.JTable tableHistory;
    // End of variables declaration//GEN-END:variables
}
