/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemenresto.view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import manajemenresto.controller.HistoryController;
import manajemenresto.model.History;

/**
 *
 * @author anr00
 */
public class FormHistori extends javax.swing.JPanel {
    HistoryController hc = new HistoryController();
    History history = new History();
    ArrayList<History> historyList = hc.getAllHistory();
    public FormHistori() {
        initComponents();
        fillTabelHistory();
    }
public void fillTabelHistory() {
        DefaultTableModel df = (DefaultTableModel)tableHistory.getModel();
        df.getDataVector().removeAllElements();
        if (historyList != null) {
            int no = 1;
            for (History history: historyList) {
                Object[] obj = new Object[5];
                obj[0] = no;
                obj[1] = history.getId();
                obj[2] = history.getDate();
                obj[3] = history.getTotal_biaya();
                obj[4] = history.getUser_id();
                ++no;
                df.addRow(obj);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboFilter = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHistory = new javax.swing.JTable();

        comboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Mingguan", "Bulanan" }));
        comboFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFilterItemStateChanged(evt);
            }
        });
        comboFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFilterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Filter:");

        tableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Id", "Tanggal", "Total Harga", "Id user"
            }
        ));
        jScrollPane2.setViewportView(tableHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFilterItemStateChanged

    }//GEN-LAST:event_comboFilterItemStateChanged

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        // TODO add your handling code here:
        if (comboFilter.getSelectedItem() == "Semua"){
            System.out.println("Masuk ke semua");
            historyList = hc.getAllHistory();
        } else if (comboFilter.getSelectedItem()=="Bulanan"){
            System.out.println("Masuk ke bulan ini");
            historyList = hc.getBulanIniHistory();
        } else if (comboFilter.getSelectedItem()=="Mingguan"){
            System.out.println("Masuk ke minggu ini");
            historyList = hc.getMingguIniHistory();
        }
        fillTabelHistory();
    }//GEN-LAST:event_comboFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableHistory;
    // End of variables declaration//GEN-END:variables
}
