/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemenresto.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manajemenresto.controller.MenuController;
import manajemenresto.controller.PesananController;
import manajemenresto.model.Menu;
import manajemenresto.model.MenuPesanan;
import manajemenresto.model.User;

/**
 *
 * @author vincentexelcio
 */
public class FormPesanan extends javax.swing.JPanel {

    /**
     * Creates new form FormPesanan
     */
    public FormPesanan() {
        initComponents();
        fillCombobox();
        fillTabelPesanan();
        textJumlahMenu.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateTotalBiaya();
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateTotalBiaya();
            }
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateTotalBiaya();
            }
        });
        comboBoxMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTotalBiaya();
            }
        });
    }
    User user;
    ArrayList<MenuPesanan> menuPesananList = new ArrayList<>();
    MenuController menuController = new MenuController();
    PesananController pesananController = new PesananController();
    double subtotal = 0;
    
    public void setUser(User user) {
        this.user = user;
    }

    public void fillCombobox() {
        comboBoxMenu.removeAllItems();
        comboBoxMenu.addItem("pilih menu");
        ArrayList<Menu> menuList = menuController.getAllMenu();
        
        if (menuList != null) {
            for (Menu menu: menuList) {
                comboBoxMenu.addItem(menu.getNama());
            }
        }
    }
    
    public void resetState() {
        textJumlahMenu.setText("");
        comboBoxMenu.setSelectedItem("pilih menu");
        textSubtotal.setText(String.valueOf(subtotal));
        fillCombobox();
        fillTabelPesanan();
    }
    
    public void updateTotalBiaya() {
        Object pilihanMenu = comboBoxMenu.getSelectedItem();
        String jumlahMenu = textJumlahMenu.getText();
    
        if (pilihanMenu == null || pilihanMenu.toString().equals("pilih menu") || jumlahMenu.isEmpty()) {
            textTotalBiaya.setText("0");
            return;
        }
    
        try {
            int jumlah = Integer.parseInt(jumlahMenu);
            Menu menu = menuController.getMenuByNama(pilihanMenu.toString());
            if (menu != null) {
                double totalBiaya = jumlah * menu.getHarga();
                textTotalBiaya.setText(String.valueOf(totalBiaya));
            }
        } catch (Exception e) {
            textTotalBiaya.setText("0");
        }
    }
    
    public void fillTabelPesanan() {
        DefaultTableModel df = (DefaultTableModel)tabelPesanan.getModel();
        df.setRowCount(0);
        
        if (menuPesananList != null) {
            int no = 1;
            for (MenuPesanan menuPesanan: menuPesananList) {
                Object[] obj = new Object[4];
                obj[0] = no;
                obj[1] = menuPesanan.getMenu().getNama();
                obj[2] = menuPesanan.getJumlahPesanan();
                obj[3] = menuPesanan.getJumlahPesanan() * menuPesanan.getMenu().getHarga();
                ++no;
                df.addRow(obj);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPesanan = new javax.swing.JTable();
        buttonTambah = new javax.swing.JToggleButton();
        buttonKonfirmasi = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        comboBoxMenu = new javax.swing.JComboBox<>();
        textJumlahMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textSubtotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textTotalBiaya = new javax.swing.JLabel();
        buttonHapus = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(536, 440));

        tabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelPesanan);

        buttonTambah.setText("tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonKonfirmasi.setText("Konfirmasi Pesanan");
        buttonKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKonfirmasiActionPerformed(evt);
            }
        });

        jLabel3.setText("Pilih Menu");

        comboBoxMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMenuActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setText("Subtotal:");

        textSubtotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        textSubtotal.setText("0");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Total Biaya:");

        textTotalBiaya.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        textTotalBiaya.setText("0");

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboBoxMenu, 0, 139, Short.MAX_VALUE)
                                .addComponent(textJumlahMenu))
                            .addComponent(textTotalBiaya)))
                    .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(textSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttonKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textJumlahMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textTotalBiaya))
                        .addGap(18, 18, 18)
                        .addComponent(buttonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapus)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSubtotal))
                .addGap(18, 18, 18)
                .addComponent(buttonKonfirmasi)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        String pilihanMenu = comboBoxMenu.getSelectedItem().toString();
        String jumlahMenu = textJumlahMenu.getText();
        int jumlah;
        
        // validasi combobox
        if (pilihanMenu.equals("pilih menu")) {
            JOptionPane.showMessageDialog(this, "Silahkan memilih menu terlebih dahulu");
            return;
        }
        
        // validasi jumlah menu
        try {
            jumlah = Integer.parseInt(jumlahMenu);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Jumlah menu harus berupa angka");
            return;
        }
        if (jumlah < 1) {
            JOptionPane.showMessageDialog(this, "Jumlah menu minimum 1");
        }
        
        Menu menu = menuController.getMenuByNama(pilihanMenu);
        
        // cek menu apakah sudah pernah dipilih
        boolean sudahDipesan = false;
        for (MenuPesanan menuPesanan : menuPesananList) {
            if (menuPesanan.getMenu().getNama().equals(menu.getNama())) {
                menuPesanan.setJumlahPesanan(jumlah);
                sudahDipesan = true;
                break;
            }
        }
        if (!sudahDipesan) {
            MenuPesanan menuPesanan = new MenuPesanan();
            menuPesanan.setMenu(menu);
            menuPesanan.setJumlahPesanan(jumlah);
            menuPesananList.add(menuPesanan);
        }
        
        // edit subtotal
        subtotal = 0;
        for (MenuPesanan menuPesanan : menuPesananList) {
            subtotal += menuPesanan.getJumlahPesanan() * menuPesanan.getMenu().getHarga();
        }
        JOptionPane.showMessageDialog(this, "menu berhasil ditambahkan");
        resetState();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void comboBoxMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMenuActionPerformed
        Object pilihanMenu = comboBoxMenu.getSelectedItem();
        
        if (menuPesananList.isEmpty() || pilihanMenu == null || pilihanMenu.toString().equals("pilih menu")) {
            textJumlahMenu.setText("");
            return;
        }
        
        for (MenuPesanan menuPesanan : menuPesananList) {
            if (menuPesanan.getMenu().getNama().equals(pilihanMenu.toString())) {
                textJumlahMenu.setText(String.valueOf(menuPesanan.getJumlahPesanan()));
                return;
            }
        }
        textJumlahMenu.setText("");
    }//GEN-LAST:event_comboBoxMenuActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        String pilihanMenu = comboBoxMenu.getSelectedItem().toString();
        
        // validasi combobox
        if (pilihanMenu.equals("pilih menu")) {
            JOptionPane.showMessageDialog(this, "Silahkan memilih menu terlebih dahulu");
            return;
        }
        
        for (int i = 0; i < menuPesananList.size(); ++i) {
            MenuPesanan menuPesanan = menuPesananList.get(i);
            if (menuPesanan.getMenu().getNama().equals(pilihanMenu)) {
                menuPesananList.remove(i);
                
                subtotal = 0;
                for (MenuPesanan menuDipesan : menuPesananList) {
                    subtotal += menuDipesan.getMenu().getHarga() * menuDipesan.getJumlahPesanan();
                }
                textSubtotal.setText(String.valueOf(subtotal));
                JOptionPane.showMessageDialog(this, "Menu berhasil dihapus");
                resetState();
                return;
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKonfirmasiActionPerformed
        boolean status = pesananController.CreatePesanan(user.getId(), menuPesananList, subtotal);
        System.out.println(user.getId());
        if (!status) {
            JOptionPane.showMessageDialog(this, "Pesanan gagal terkonfirmasi");
            return;
        }
        JOptionPane.showMessageDialog(this, "Pesanan berhasil terkonfirmasi");
        menuPesananList.clear();
        subtotal = 0;
        resetState();
    }//GEN-LAST:event_buttonKonfirmasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JToggleButton buttonKonfirmasi;
    private javax.swing.JToggleButton buttonTambah;
    private javax.swing.JComboBox<String> comboBoxMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPesanan;
    private javax.swing.JTextField textJumlahMenu;
    private javax.swing.JLabel textSubtotal;
    private javax.swing.JLabel textTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
