/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manajemenresto.view;

import javax.swing.JOptionPane;
import manajemenresto.controller.MenuController;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import manajemenresto.model.Menu;
import manajemenresto.view.FormLogin;

/**
 *
 * @author vincentexelcio
 */
public class FormMenu extends javax.swing.JPanel {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        fillCombobox();
        fillTabelMenu();
        buttonBatal.setVisible(false);
    }
    
    MenuController menuController = new MenuController();
    Menu SELECTED_MENU = new Menu();
    
    public void fillCombobox() {
        comboBoxMenu.removeAllItems();
        comboBoxMenu.addItem("pilih menu");
        ArrayList<Menu> menuList = menuController.getAllMenu();
        
        if (menuList != null) {
            for (Menu menu: menuList) {
                comboBoxMenu.addItem(menu.getNama());
            }
        }
    }
    
    public void resetState() {
        textNamaMenu.setText("");
        textHarga.setText("");
        SELECTED_MENU = new Menu();
        comboBoxMenu.setSelectedItem("pilih menu");
        fillCombobox();
        fillTabelMenu();
    }
    
    public void fillTabelMenu() {
        DefaultTableModel df = (DefaultTableModel)tabelMenu.getModel();
        df.getDataVector().removeAllElements();
        ArrayList<Menu> menuList = menuController.getAllMenu();
        
        if (menuList != null) {
            int no = 1;
            for (Menu menu: menuList) {
                Object[] obj = new Object[3];
                obj[0] = no;
                obj[1] = menu.getNama();
                obj[2] = menu.getHarga();
                ++no;
                df.addRow(obj);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNamaMenu = new javax.swing.JTextField();
        textHarga = new javax.swing.JTextField();
        buttonHapus = new javax.swing.JToggleButton();
        comboBoxMenu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buttonCari = new javax.swing.JToggleButton();
        buttonTambah = new javax.swing.JToggleButton();
        buttonEdit = new javax.swing.JToggleButton();
        buttonBatal = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setBackground(new java.awt.Color(143, 40, 50));

        tabelMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelMenu);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Menu");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga");

        buttonHapus.setText("hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        comboBoxMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMenuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cari Menu");

        buttonCari.setText("cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        buttonTambah.setText("tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonEdit.setText("edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonBatal.setText("batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonTambah)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonBatal)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCari))
                            .addComponent(comboBoxMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logout)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCari)
                        .addComponent(buttonBatal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHapus)
                    .addComponent(buttonTambah)
                    .addComponent(buttonEdit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        String namaMenu;
        double harga;
        
        namaMenu = textNamaMenu.getText();
        try {
            harga = Double.parseDouble(textHarga.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka");
            return;
        }
        boolean status = menuController.CreateMenu(namaMenu, harga);
        
        if (!status) {
            JOptionPane.showMessageDialog(this, "Menu gagal tersimpan");
            return;
        }
        JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan");
        resetState();
        
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        String pilihanMenu = comboBoxMenu.getSelectedItem().toString();
        
        if (pilihanMenu.equals("pilih menu")) {
            JOptionPane.showMessageDialog(this, "Silahkan memilih menu terlebih dahulu");
            return;
        }
        
        SELECTED_MENU = menuController.getMenuByNama(pilihanMenu);
        
        if (SELECTED_MENU == null) {
            JOptionPane.showMessageDialog(this, "Gagal mendapatkan menu");
        }
        
        textNamaMenu.setText(SELECTED_MENU.getNama());
        textHarga.setText(String.valueOf(SELECTED_MENU.getHarga()));
        
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        Menu menuBaru = new Menu();
        
        if (SELECTED_MENU.getNama() == null) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Menu terlebih dahulu");
            return;
        }
        
        menuBaru.setNama(textNamaMenu.getText());
        try {
            menuBaru.setHarga(Double.parseDouble(textHarga.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka");
            return;
        }
        
        boolean status = menuController.updateMenuByNama(SELECTED_MENU.getNama(), menuBaru);
        
        if (!status) {
            JOptionPane.showMessageDialog(this, "Menu gagal diubah");
            return;
        }
        JOptionPane.showMessageDialog(this, "Menu berhasil diubah");
        resetState();
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        resetState();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        
        if (SELECTED_MENU.getNama() == null) {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Menu terlebih dahulu");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin?", "Konfirmasi", 2);
        if (confirm == JOptionPane.CANCEL_OPTION || confirm == JOptionPane.NO_OPTION) {
            return;
        }
        boolean status = menuController.deleteMenuByNama(SELECTED_MENU.getNama());
        
        if (!status) {
            JOptionPane.showMessageDialog(this, "Menu gagal dihapus");
            return;
        }
        JOptionPane.showMessageDialog(this, "Menu berhasil dihapus");
        resetState();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void comboBoxMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMenuActionPerformed
        Object pilihanMenu = comboBoxMenu.getSelectedItem();

        if (pilihanMenu != null && !pilihanMenu.toString().equals("pilih menu")){
            buttonBatal.setVisible(true);
        }
        else {
            buttonBatal.setVisible(false);
        }
    }//GEN-LAST:event_comboBoxMenuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        parentFrame.setVisible(false);
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JToggleButton buttonCari;
    private javax.swing.JToggleButton buttonEdit;
    private javax.swing.JToggleButton buttonHapus;
    private javax.swing.JToggleButton buttonTambah;
    private javax.swing.JComboBox<String> comboBoxMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTable tabelMenu;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textNamaMenu;
    // End of variables declaration//GEN-END:variables
}
